# -- Makefile

import pfDevTools

# -- We need pf-dev-tools version 1.x.x but at least 1.0.5.
pfDevTools.requires('1.0.5')

env = pfDevTools.SConsEnvironment(PF_CORE_TEMPLATE_REPO_TAG='v0.0.4_fullres_for_openFPGATutorials')

env.OpenFPGACore('src/config.toml')
