#
# openFPGA core config file
#

[Platform]
name = "01 BasicTemplate"
image = "../../assets/platform-image.png"
short_name = "fpgatut01"
category = "Tutorials"
description = "openFPGA tutorials is a collection of code samples and resources to learn openFPGA development."
info = "info.txt"

[Build]
version = "0.0.1"

[Author]
name = "dm"
icon = "../../assets/core-author-icon.png"
url = "https://github.com/DidierMalenfant/openFPGA-tutorials"

[Bitstream]
source = "_build/pfCoreTemplate/src/fpga/output_files/ap_core.rbf"

[Video]
width = 320
height = 240
aspect_w = 4
aspect_h = 3
rotation = 0
mirror = 0
